name: ui_design
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.3
  percent_indicator: ^4.2.3
  google_fonts: ^4.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/d20dfd6cb15da5efd26035008cb51b68.jpg
    - assets/Virtual_Office_empty-1024x768.jpg
    - assets/08burner-class-mediumSquareAt3X.jpg
    - assets/cb-background-hd-for-photoshop-photo-editing-11637450215ih1om0bqxr.jpg
    - assets/person5.jpg
    - assets/person2.jpg
    - assets/person6-1.jpg
    - assets/person4-1.jpg
    - assets/person-5.jpg
    - assets/person-1.jpg
    - assets/earth.png
    - assets/more.png
    - assets/people.png
    - assets/user.png
    - assets/live-streaming.png
    - assets/messenger.png
    - assets/wallpaperflare.com_wallpaper (6).jpg
    - assets/274852-wallpaper-1080-1920.jpg
    - assets/Paris-Night-France-City-Dark-Eiffel-Tower-iphone.jpg
    - assets/Shibuya-Japan-iphone-8.jpg
    - assets/hong-kong-hong-kong-island-lights-future-thumbnail.jpg
    - assets/96-Lock-Screen-Wallpapers-HD-WallpaperYou.jpg
    - assets/pic.jpg
    - assets/download.jpg
    - assets/download (1).jpg
    - assets/download (2).jpg
    - assets/download (3).jpg
    - assets/download (4).jpg
    - assets/imdb_logo._CB410901634_.png
    - assets/unnamed.jpg
    - assets/dots.png
    - assets/colleagues-giving-fist-bump.jpg

    - assets/youtube/dont-like (1).png
    - assets/youtube/download.png
    - assets/youtube/like (2).png
    - assets/youtube/mix.png
    - assets/youtube/share (1).png
    - assets/youtube/WhatsApp Image 2023-07-13 at 13.17.24.jpg
    - assets/youtube/WhatsApp Image 2023-07-13 at22 13.17.24.jpg
    - assets/youtube/WhatsApp Image 2023-07-13 1at 13.17.23.jpg

    - assets/instagram/bag.png
    - assets/instagram/bookmark.png
    - assets/instagram/chat.png
    - assets/instagram/heart.png
    - assets/instagram/house-black-silhouette-without-door.png
    - assets/instagram/messenger.png
    - assets/instagram/more.png
    - assets/instagram/search-interface-symbol.png
    - assets/instagram/send.png
    - assets/instagram/user.png
    - assets/instagram/video.png
    - assets/instagram/more2.png
    - assets/instagram/images.png



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
